<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/27
 * Time: 8:43
 */

namespace app\common\model;

use app\common\model\Base;
class Admin extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public $pk = 'id';
    protected $table = 'lin_admin';
}