<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/6
 * Time: 12:26
 */

namespace app\common\model;

use app\common\model\Base;
class ArticleTag extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $table = 'lin_article_tag';
    protected $pk = ['aid', 'tid'];
}