<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/1
 * Time: 15:41
 */

namespace app\common\model;

use app\common\model\Base;
class Category extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public $pk = 'cid';
    protected $table = 'lin_category';
}