<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/1
 * Time: 15:41
 */

namespace app\common\model;


class Category extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public $pk = 'cid';
    protected $table = 'lin_category';

    public function articles()
    {
        return $this->hasMany('Article')->field('article');
    }
}