<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/2
 * Time: 9:34
 */

namespace app\common\model;

class Tag extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public $pk = 'tid';
    protected $table = 'lin_tag';

    public function artciles()
    {
        return $this->belongsToMany('\\app\\common\\model\\article',
            'lin_article_tag', 'tid','tid');
    }
}