<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/2
 * Time: 9:34
 */

namespace app\common\model;

use app\common\model\Base;
class Tag extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public $pk = 'tid';
    protected $table = 'lin_tag';
}