<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/5/22
 * Time: 14:51
 */

namespace app\common\controller;

use app\common\controller\Base;
class AdminBase extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stubz
//        if(!session('username'))
//            return $this->redirect(url('admin/Security/login'));
//        if(!session('is_admin'))
//            return $this->error('你不是管理员,不能进入后台','/');
//        $data = [
//            'admin_name' => session('username')
//        ];
//        $this->assign($data);
    }

    public function suc($msg)
    {
        if(is_array($msg)){
            $result =  array_merge(['ret'=>1],$msg);
        }elseif(is_string($msg)){
            $result =  ['ret'=>1,'msg'=>$msg];
        }else{
            $result = ['ret'=>1,'msg'=>'操作成功'];
        }
        return json($result);
    }
    public function err($msg)
    {
        if(is_array($msg)){
            $result =  array_merge(['ret'=>0],$msg);
        }elseif(is_string($msg)){
            $result =  ['ret'=>0,'msg'=>$msg];
        }else{
            $result = ['ret'=>0,'msg'=>'操作成功'];
        }
        return json($result);
    }
}