<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/5/22
 * Time: 14:51
 */

namespace app\common\controller;

use app\common\controller\Base;
class AdminBase extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stubz
//        if(!session('username'))
//            return $this->redirect(url('admin/Security/login'));
//        if(!session('is_admin'))
//            return $this->error('你不是管理员,不能进入后台','/');
//        $data = [
//            'admin_name' => session('username')
//        ];
//        $this->assign($data);
    }

}