<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/1
 * Time: 16:11
 */

namespace app\common\controller;

use app\common\controller\Base;
use app\common\repository\CategoryRepository;
use app\common\repository\TagRepository;
use app\common\repository\ArticleRepository;
class IndexBase extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $assign = [
            'categorys' => CategoryRepository::getByPid(1),
            'tags' => TagRepository::getTags(),
            'top_articles' => ArticleRepository::getTopArticle(),
            'color' => ['label-info'=>1, 'label-primary'=>2, 'label-success'=>3, 'label-info'=>4,
                'label-warning'=>5, 'label-danger'=>6,],
        ];
        $this->assign($assign);

    }
}