<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/6/1
 * Time: 16:11
 */

namespace app\common\controller;

use app\common\controller\Base;
use app\common\repository\CategoryRepository;
use app\common\repository\TagRepository;
use app\common\repository\ArticleRepository;
class IndexBase extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}